version: "3.8"
  
services:
  database:
    build: ./sqlserver
    container_name: "fibonacci_db"
    ports:
     - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
